### PR TITLE
Added layout to Leaderboard App

### PR DESCRIPTION
**Pull request by gjuliao**
## Requirements
- Using Gitflow
- No linter errors
- Using Webpack
- Plain Html

### CODE REVIEW

**Comment by julie-ify** [comment]
Hi @gjuliao,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

### Your readme file is blank. Kindly update your readme using the template

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by ha-manel — COMMENTED** [review]
# STATUS: INVALID 🔴 
Hi @gjuliao 
I'm sure you put a lot of effort into this project but this PR is invalid because your README file is empty😓 kindly copy the content of this [template](https://github.com/microverseinc/readme-template) and replace the placeholder text with information about your project 👍  

Kindly fix the issue and submit the PR for review again 👍 
Best of luck!

------
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by gjuliao** [comment]
Hi Manel,

Readme file is in the main code.  Please see the code besides the pull
request.

https://github.com/gjuliao/leaderboard_js @ha-manel 

Thank!

**Comment by ha-manel** [comment]
@gjuliao Kindly add it for this branch too 😅

**Review by omarsalem7 — APPROVED** [review]
Hi @gjuliao 😊, 

# STATUS: APPROVED! 🥇 💯 

giphy

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 🚀 
Congratulations! 🎉 

## Highlights
- There is no linter error present ✔️
- The Pull Request has a proper description ✔️
- The project has met all the technical aspects you needed for this project. Keep rocking!  ✔️


Cheers and Happy coding!👏👏👏

## Optional suggestions

- [ ] [OPTIONAL] I noticed that some of your commit messages are not capitalized and not in the imperative tense. The commit message should be written in the imperative tense and capitalized. [Read more about how to write descriptive commit messages](https://www.freecodecamp.org/news/level-you-up-to-awesome-commit-messages-a85558cb90e8). For your next commit don't forget to write good and descriptive commit messages.

- [ ] [OPTIONAL] Kindly consider fixing the broken license MIT link and adding your own license. 


_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
